### ISSUE TITLE
Suggestion: Loot Overview Tab

### ISSUE THREAD

**Issue by SuneKristensen98** [CoreLootManager/CoreLootManager#409]
I run several raids with CLM, and due to the high amount of items dropping here in WOTLK, my raiders have a hard time of tracking what dropped throughout the raid. They have asked me to request for this feature (if possible)

What they want:
A table of some sort, that simply displays the items that have dropped in the raid, which are yet to be auctioned out for DKP.

They would also like to see the items that have already been auctioned out, with the name of the person winning it, and the price he/she paid. This is however a "bonus feature" since the primary would be to get an easy overview.

**Comment by crimsoncoyote** [comment]
The second part they can find on the history tab in the CLM GUI by using appropriate filters.

**Comment by SuneKristensen98** [comment]
Yeah they are aware of that, but it would be kinda easier having in one joint overview if that makes sense?
