### ISSUE TITLE
Suggestion: Decay options

### ISSUE THREAD

**Issue by Calvicious** [CoreLootManager/CoreLootManager#480]
Right now, the Decay option is decaying both EP and GP points, but we would like to decay only the EP points. It would be great if we could choose what we want to decay, let's say, only EP, only GP or both.
Neat little setting which would help us a lot!

Thanks in advance! :)

**Comment by SamMousa** [comment]
That breaks ep/gp as a system though. New players will almost always have priority until they catch up with older players in gear points. Also at some point due to the ep decay your priority will not really go up anymore due to the fact that there's a limit to ep gained which creates a soft limit on total EP.

This means that the GP component will be more significant and you effectively end up with a system without EP component where you distribute loot purely based on loot history.

**Comment by Calvicious** [comment]
I would totally agree with you if you would use the system for an extensive amount of time. But as I already explained on Discord, we erase the points every season start, so we only use them for about 4-5 months every cycle. If we would decay the GP as well, the ratios would be very volatile, with very high ratios over time, because naturally (especially on retail where we play) ppl spend more GP at the start of the season, and much less after 1-2 months (gaining a lot of BiS loot from Mythic+ and Crafting).

If someone joins throughout the season, we use a formula to determine their starting GP. Your EP also cannot be capped in this short amount of time if you decay it weekly, especially if you slightly increase the decay% over the season. We reward EP outside raid activites, but also deduct EP for violations. With these kind of settings and rules we manage to keep the ratios tighter, but also leaving the room for ppl to take 2-3 items in a row later in the season if they didn't spend that much until that point, and the new players have a chance to take a loot after 2-3 weeks.

You can't really say how this or that will work with decay until you know how the individual system is set up. You can set up an EP/GP system in a million way. :D We used and will continue to use the decay only on EP, it works for us, maybe it does for others too.

I quite like this addon (it's a big thing for me to say :D), it's quite neat, transparent and easy to use. The option to choose what to decay would just made our job that easier, and hopefully not that hard for Lantis to setup in the addon.^^
