### ISSUE TITLE
Can't add or retract GP after new drop-down menu

### ISSUE THREAD

**Issue by Ceillia** [CoreLootManager/CoreLootManager#490]
**Describe the bug**
Can't add or retract GP after new drop-down menu
When adding or retracting GP manually, it instead adds or retracts EP

**To Reproduce**
Simply try and add GP manually (see screens below)

**Expected behavior**
GP was expected to be added - not EP

**Screenshots**
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/77c17131-d47c-4b12-82cc-75632b1ceee9)
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/51082d50-cb22-4e37-bda8-fae288b3d7d6)

EPGP before:
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/52f3bc0a-74e9-46cb-bf1d-aea88cb153b3)

EPGP after:
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/e39246d1-7862-4b53-b49d-37cce142fac0)

**AddOn and Game Version:**
 v4.1.1
 WotLK Classic

**Comment by lantisnt** [comment]
Hi
Thank you for the report. This is an unfortunate regression and the UI changes shouldnt have been released

**Comment by Ceillia** [comment]
> 

All good, thanks :)
Rolled back to v4.1.0 for now and all works again.
