### ISSUE TITLE
Spammage upon logging in after update

### ISSUE THREAD

**Issue by Ceillia** [CoreLootManager/CoreLootManager#512]
**Describe the bug**
Upon logging into the game I'm now getting spammed by endless counts of ... "lines" (see below)
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/4c285894-8282-4fb5-a4e4-4cd6b65bdde5)

**To Reproduce**
Just updated to lateset release and logged on

**Expected behavior**
Nothing

**Screenshots**
![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/05a005bd-3ab3-4b1f-8794-73c6a950724a)

![image](https://github.com/CoreLootManager/CoreLootManager/assets/123099102/777fae30-f17d-420c-8b7c-1fa0a34c66ef)

**AddOn and Game Version:**
Lateset release, Wrath Classic

**Comment by Ceillia** [comment]
Update...
It appears the spammage keeps coming every little change add to the standings
Raiding is spammed away

**Comment by romdeau23** [comment]
It's in `ClassicLootManager\Modules\Rosters\RosterManager\Roster.lua` on line 134, in function `IsProfileInRoster`.

Remove the print line until the addon is updated.

**Comment by lantisnt** [comment]
Closed in v4.4.1
