### ISSUE TITLE
Out of guild member able to view roster DKP table

### ISSUE THREAD

**Issue by raimondi1337** [CoreLootManager/CoreLootManager#530]
**Is your request related to a problem? Please describe.**
I'm not the loot master so I can't say for sure, but according to my loot master, there doesn't seem to be a way for non-guild members to get access to viewing the DKP table of the rest of the guild, and I can only see my own using the whisper command. Opening the CLM addon is just all blank panes.

If this is already a feature I can't find any documentation for it.

**Describe the solution you'd like**
Be able to be added to the roster by name, and have the DKP info propagate to me regardless of guild.

**Describe alternatives you've considered**
Whisper GM for screenshot before raid 🥴 

**Additional context**
I participate in two guilds on one character and can't be in both of them in game.

**Comment by lantisnt** [comment]
Closed by #548
