### ISSUE TITLE
Visual information in BID window for Master Looter and other raiders when people press PASS button 

### ISSUE THREAD

**Issue by Waldano25** [CoreLootManager/CoreLootManager#542]
Visual information in BID window for Master Looter and other raiders when people press PASS button will be perfect
As Master Looter im so tired to always ask people: "Will you bid more? Will you or pass?" before closing auction.

For example, there are 3-5 people in the auction for an item, bids are stalled, and as a master looter I have to ask people they will pass or will they raise before closing the bidding window. If this information is visually displayed when the pass button is pressed, the master looter will not need to ask anything in either voice or raid-chat.

**About realisation visual information:**

**1.** Best way = if player push PASS button his bid line (his name and bid number) become grey in auction window for master looter.
**2.** If all raid can see if player pass and his bid become grey in bid window.
Its gonna be perfect for guild with "open auction DKP-system"

Not sure if paragraph 2 possible or not, but at least paragraph 1 must be possible.

**P.S.**
Just checked in photoshop some of my bid window screenshots.
Made one bid line grey color - looks nice but little hard to instant recognise.

Maybe better make if player pass = his bid line in auction window become:
 ~~PlayerNickname 100dkp~~ 
 or  
 PlayerNickname ~~100dkp~~
 
 If player change his mind and want bid again - he must again open bid window and rise bid to remove crossed out line.

**Comment by Mushoz** [comment]
To add to this: Would be even more amazing if the auction automatically stops if everyone has passed. That way the auction can be fully automated to skip as much unneeded waiting as possible.

**Comment by Mushoz** [comment]
I do indeed mean all raid members.

**Comment by lantisnt** [comment]
All raid members passed on all items? I find that case extremely rare.

If you're auctioning only one item at a time... that's an issue of itself ^^

**Comment by Waldano25** [comment]
**About realisation visual information:**

**1.** Best way = if player push PASS button his bid line (his name and bid number) become grey in auction window for master looter.
**2.** If all raid can see if player pass and his bid become grey in bid window its gonna be perfect for guild with "open auction DKP-system"

Not sure if paragraph 2 possible or not, but at least paragraph 1 must be possible.

**Comment by Waldano25** [comment]
> All raid members passed on all items? I find that case extremely rare.
Yeah no one gonna wait til all passes - as Master Looter for 2+ years its ALWAYS ONE PERSONE who always "Sry, wat afk - I pass, i pass!"

**Comment by lantisnt** [comment]
Graying out sounds good. Was thinking about some background color but gray text color isn't bad idea

**Comment by Waldano25** [comment]
> Graying out sounds good. Was thinking about some background color but gray text color isn't bad idea

Just checked in photoshop some old bid window screenshot.
Made one bid line grey color nice but little hard to instant recognise.

Mayber better if player pass his bid line in auction window become:
 ~~PlayerNickname 100dkp~~
 
 If player change his mind and want bid - he must again open bid window and rise bid to remove crossed out line.

**Comment by Waldano25** [comment]
> @Waldano25 BId passes look kinda cool ![image](https://private-user-images.githubusercontent.com/43088589/311449755-363b5e8b-247d-4b92-8ad0-ce45e8ba0b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMDM0NTUsIm5iZiI6MTcxMDAwMzE1NSwicGF0aCI6Ii80MzA4ODU4OS8zMTE0NDk3NTUtMzYzYjVlOGItMjQ3ZC00YjkyLThhZDAtY2U0NWU4YmEwYjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE2NTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODA5NGIwZDQzZTI4NzQzMTgyYWYxYmI1YmJiZGE2MTQ2MGVjYmYzMzhiYjNkMDVhNzg2YWM1NDA0MGY5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AV5NtBTS9D1JATWO8kJDXFxRJCF0DxD76hJ5lXn_zIA)
> 

Looks perfect!

> But I wonder if bit cancels should be displayed also or not hmmm

You mean close bid window should displayed as pass?

People very often close bid window accidentaly and reopen after.
So i think action as close window better not react as PASS (grey text) in bid line.
