### ISSUE TITLE
CLM massive lags for the whole raid

### ISSUE THREAD

**Issue by thedoctorl08** [CoreLootManager/CoreLootManager#553]
**Describe the bug**

Whenever someone enters the raid or leaves or loot is rolled out for bidding or loot is awarded or DKP is giving out the whole raid /guild everyone who is on roster has a 5 - 10 second lags.

We use CLM for our classic guildes for almost 2 years now since your updates in early april clm is being a pain in the ass and everyone is massive laggin.

please stop whatever u have been doing we dont want to change addon after we have been using it for such a long time.

**AddOn and Game Version:**
 - 
 - v5.0.1

**Comment by thedoctorl08** [comment]
Dear Sirs,

please debugg the lags a raid with CLM in wow classic is not possible anymore the lags are too heavy

**Comment by thedoctorl08** [comment]
and I got kicked and discord lol holyshit haha what bad thing did I do cant even check where I can pay well that makes it easy xD

**Comment by SamMousa** [comment]
So to summarize:
- You don't have to pay
- But you also can't demand stuff from open source maintainer.
- The tone you use in your message is definitely not a friendly help request, if that's what you think is friendly ask your parents for some more parenting.

Have fun switching to another add-on, I'm sure that community is happy to have another spoiled little child join them.
