### ISSUE TITLE
Chat Bidding Broken

### ISSUE THREAD

**Issue by sedlarizona** [CoreLootManager/CoreLootManager#557]
Simply always get "Chat Bidding is currently disabled." every time we attempt to test with `!bid`, even though `!dkp` works - so clearly chat commands are enabled.

![image](https://github.com/CoreLootManager/CoreLootManager/assets/168690148/69019ca3-d2e5-4fe1-9370-d1e1a94fbbec)

**Comment by crimsoncoyote** [comment]
Chat bidding hasn't functioned in almost 2 years. This is by design. References to chat bidding will be removed in the future.

**Comment by sedlarizona** [comment]
Ah, unfortunate. Was hoping to not force guildies into downloading an addon if the chat bidding worked as well. Thank you for the response.
