### ISSUE TITLE
JSON export timestamps are incorrect

### ISSUE THREAD

**Issue by paradoxguild** [CoreLootManager/CoreLootManager#562]
When exporting a roster's standing via `/clm export`, timestamps are not correct.

For example, we ran an MC on 5/20/2024, and the timestamp of all loot items are resolving to 1970.

Here is an example timestamp: `1716258067` which resolves to `Date Tue Jan 20 1970 13:44:18 GMT-0700 (Mountain Standard Time)`.

Is there some other sort of logic to these timestamps to get them to resolve to the correct date? Does a base timestamp need to be added to the timestamps that are output?

The settings that I used are:
- Standings [X]
- Loot History [X]
- JSON [X]
- Begin: Day=1, Month=January, Year=2019
- Finish: Day=31, Month=December, Year=2024
- I selected the one Roster we use for real standings, rather than a test roster for displaying how we award/spend points
- I Included `Everyone` under `Profiles`

**Comment by lantisnt** [comment]
Unable to recreate any invalid timestamps. 
Also, the provided example timestamp resolves properly:
![image](https://github.com/CoreLootManager/CoreLootManager/assets/43088589/7ceda07c-6f7a-4db8-bbb4-f30873a3eeed)
Cllsing as not a bug.
