### ISSUE TITLE
Cata Classic - Profile creation minimum level slider needs update to 85

### ISSUE THREAD

**Issue by crimsoncoyote** [CoreLootManager/CoreLootManager#564]
In CLM v5.0.4, the minimum level slider in the Profiles tab is still capped at level 80 in Cataclysm Classic. This needs to be updated to allow it to go to 85.

![image](https://github.com/CoreLootManager/CoreLootManager/assets/1790997/64735ab2-f674-4a46-8f81-5006ba494aef)

**Comment by lantisnt** [comment]
Completed with #567
