### ISSUE TITLE
auto loot award for disenchanting, blue/green items special items like orbs or shards

### ISSUE THREAD

**Issue by quasie-1** [CoreLootManager/CoreLootManager#571]
1. make a line where you can set who your disenchanter is so when the award to disenchant will award the item to that person. 
2.  have some sort of a pack mule option that you can auto loot items  "award" then to a player without really seeing it.
3. have it where predetermined items like legendary shards, orbs etc can be sent to a person(s)
all of these items could be selected as options in the "raid" tab

**Comment by lantisnt** [comment]
1. Its in there
2. I have no idea what you mean. Do you mean autotrade/auto-assign from corse awarded or disenchanted items? Then it's in there
3. At this moment there is no plan to add this complex functionalities that garguls packmule provides

**Comment by quasie-1** [comment]
you just told me in your discord its not in there for item 1
