### ISSUE TITLE
Can't start the raid in the new world boss raid in classic wow SoD

### ISSUE THREAD

**Issue by guanggevwu** [CoreLootManager/CoreLootManager#579]
**Describe the bug**
It is the first time I use this addon. Somehow after I created the event, and then I right clicked the event and tried to start the raid, it says "You are not in the raid.". Is there a work around.

Edit: the correct English version of the error is "You are not in the raid."

**Comment by lantisnt** [comment]
Sounds like user error. Can you post a screenshot?
After you create a raid you need to right click it to select it and start it

**Comment by guanggevwu** [comment]
I will post the screenshot after I get home. Since this is the first time I use the addon, I would like to know if I have to be in the raid instance to start the raid.

**Comment by lantisnt** [comment]
I recommend discussing this kind of issues on discord: https://discord.gg/Qjn8KdD8yt
1) No you do not need to be in an instance to start a raid, but you need to be in inagame raid (not party).
2) If there are some bosses missing for P4 let me know, I might have missed some?

**Comment by guanggevwu** [comment]
![image](https://github.com/user-attachments/assets/8380ffe6-88c9-4bc5-917e-d49a5943530c)
I right clicked the event and tried to start the raid. 
The error shown in the chat window is "你不在团队/团本活动中。"
This means (in CoreLootManager/ClassicLootManager/Locale/zhTW.lua):
-- ClassicLootManager/Modules/Raids/RaidManager/RaidManager.lua:342
CLM.L["You are not in the raid."] = "你不在团队/团本活动中。"

But I am actually in a raid group.

**Comment by lantisnt** [comment]
That suggests you actually created the raid without having the profile. Create a profile for yourself first.

**Comment by guanggevwu** [comment]
Create the profile information (for example, import from guild) then I can start the raid.
