### ISSUE TITLE
Item Override with Dynamic

### ISSUE THREAD

**Issue by MetalJacx** [CoreLootManager/CoreLootManager#580]
**Is your request related to a problem? Please describe.**
We are using EPGP with loot council. So this is a two tier problem.
First,
There are items, that are highly contested that we would like to price higher and not the entire slot. There is also items that are for quests like Sinew and Eyes that we would like to manually control. Sinew it not consider equipment so has no price and Eyes are consider trinket and just doesn't match our goal.

Second,
In searching the discord for similar issue it was mention to do custom auction. The thing is we do use CLM to pass out gear as we have to make a vote and we use RCLC to pass out gear. So it would be nice in the override section to just be able to add the item there.

**Describe the solution you'd like**
Be able to manual assign Item Values when using Dynamic and be-able to preset item values without having to use auction function and assign under the roster configuration. 

OverAll, I rather not mess with multipliers and very simple where `itemid=##gp`. If the itemID detected in override then that price will be the price no matter what is defined in dynamic.

**Describe alternatives you've considered**
Right now the alternatives is manually adjust, but that can lead to errors specially if the main master loot is out for the week and things get missed in the delegation.

**Additional context**
None, but thank you for your time.

**Comment by lantisnt** [comment]
This function exists in CLM
