### ISSUE TITLE
(retail wow) Cannot open configuration menu

### ISSUE THREAD

**Issue by pwilhelm67** [CoreLootManager/CoreLootManager#583]
**Describe the bug**
(retail wow) Cannot open configuration menu from the minimap button. I'm new and not sure if there's another way to open the config menu. CLM v5.1.2 downloaded with Curseforge Client. CLM is the only addon loaded. When I click config it shows the following error:
---
Message: Interface/AddOns/ClassicLootManager/MinimapIcon.lua:160: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
Time: Sun Aug  4 20:23:07 2024
Count: 1
Stack: Interface/AddOns/ClassicLootManager/MinimapIcon.lua:160: attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@Interface/AddOns/ClassicLootManager/MinimapIcon.lua"]:160: in function `func'
[string "@Interface/AddOns/ClassicLootManager/Libs/LibUIDropDownMenu/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:233: in function <...DropDownMenu/LibUIDropDownMenu/LibUIDropDownMenu.lua:199>
[string "@Interface/AddOns/ClassicLootManager/Libs/LibUIDropDownMenu/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:453: in function <...DropDownMenu/LibUIDropDownMenu/LibUIDropDownMenu.lua:452>

Locals: (*temporary) = nil
(*temporary) = "Core Loot Manager"
(*temporary) = "attempt to call global 'InterfaceOptionsFrame_OpenToCategory' (a nil value)"
addonName = "Core Loot Manager"
---

**To Reproduce**
1. Right click CLM minimap icon
2. Click on Configuration
3. See error

**Expected behavior**
Config menu opens.

**Screenshots**
![image](https://github.com/user-attachments/assets/1a8741a8-eee2-460d-80a4-696667394685)
![image](https://github.com/user-attachments/assets/ec804724-be43-437e-bab1-d422797d16ed)

**AddOn and Game Version:**
 - Retail v11.0.0 (55939)
 - CLM v5.1.2

**Additional context**
If there's a slash command or something to pullup the config please let me know, I didn't see one in the wiki or through playing with the addon in game. Would love to use CLM in my guild for the upcoming expansion. Please let me know if I can get any other info for you, thanks

**Comment by Liukus** [comment]
It would appear that, as usual, on a major release blizzard has relocated the functions and calls to them. From my quick looking it appears that Blizzard_Settings_Shared/Blizzard_Settings.lua is now using a class called Settings with the function OpenToCategory instead of the InterfaceOptionsFrame_OpenToCategory.

**Comment by lantisnt** [comment]
That is cortect. The release time is a bit unfortunate as im on holidays. Ill fix this once im back
