### ISSUE TITLE
Add support for Blizzard's "addon compartment" feature 

### ISSUE THREAD

**Issue by KatyPurry** [CoreLootManager/CoreLootManager#589]
Hello,
Is it possible to add the [addon compartment](https://wowpedia.fandom.com/wiki/Addon_compartment) feature ?
Thank you

**Comment by lantisnt** [comment]
Addon compartment is supported since DF. Did it stop working after todays release?

**Comment by KatyPurry** [comment]
My bad ! It's working I didn't see the addon on my list
