### ISSUE TITLE
[TWW] List Filling not working

### ISSUE THREAD

**Issue by lantisnt** [CoreLootManager/CoreLootManager#593]
Previously, when items were looted into my bag, they would automatically show up on the Auctioning window. Last night I had to manually add them. [original message](https://discord.com/channels/813686248841019392/1283643944969965639/1283643944969965639)

![image](https://github.com/user-attachments/assets/0ac5a202-a770-4501-bf1d-d60ffc80b02a)

**Comment by lantisnt** [comment]
Seems to be related to loot method `GetLootMethod()`. Disabling `Group Loot Only` solves the issue temporarily

**Comment by msuter-cbre** [comment]
Looking at this issue I was checking the tooltips next to the "Fill auction list" on the left, and comparing them to the "Loot Only" checkboxes to their right. I'm not sure if "Fill auction list from corpse" is mutually exclusive with "Master Loot Only", and the same for "Fill auction list with looted items" is mutually exclusive with "Group Loot Only". If this is the case, it may be beneficial to update the tooltip for "Group Loot Only". Currently it reads like this -
![image](https://github.com/user-attachments/assets/8fd6b09d-a0e0-4b18-92dc-2ebf98a90eea)
If these checkboxes are mutually exclusive, it might be more clear to have the tooltip read "Fill from __looted items__ only if you are using Group Loot"
