### ISSUE TITLE
Add specification on Manual adjustment to all applying negative Award value as Spent instead of Received

### ISSUE THREAD

**Issue by msuter-cbre** [CoreLootManager/CoreLootManager#606]
**Is your request related to a problem? Please describe.**
We started using Core Loot Manager brownfield for WoW SoD Phase 5, and as a result I've inputted all of our DKP standing information manually from a spreadsheet. We were tracking DKP awards and spent values separately so I entered it all in manually using positive values for awards, and negative values for Spent.

Due to the way Manual adjustment works, all values whether negative or positive get filed under the Received column so the data is inaccurate in terms of reflecting what raiders have currently spent and received. This does not impact the DKP column as that balances out fine. This is more of a request so that we can have as accurate of data as possible in CLM.

**Describe the solution you'd like**
Would like an additional dropdown under Management so we can choose Spent or Received as the destination for the manual adjustment of value. The Award value can still take a positive or negative and the new dropdown would determine if it's an add or remove depending on where that adjustment happens. For example, if it's a manual adjustment on Spent, for value 6, it would add 6 to the raiders spent column, and then deduct 6 from their DKP. This would allow it to be an addition that can work independently from how Manual adjustments work today and require no change to the existing Received manual adjustment process.

**Describe alternatives you've considered**
A workaround of course that we are using now is just to manually adjust their DKP with a negative value for DKP spent and it files it incorrectly under Received.

**Additional context**
Here is an example of 3 raiders that only have starter DKP, but spent each, 1, 2, and 3 DKP on gear. Instead if showing positive 1, 2, and 3 in the Spent column, it's filed under Received as negative values.
![image](https://github.com/user-attachments/assets/f2ee5abc-7393-4d3c-aeef-c31cdfcde418)

**Comment by lantisnt** [comment]
Im not a fan of exposing spent part for dkp however if you want to do it once there is Quick and dirty solution i can give you. Discord however might be better for this
